version: 0.10.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
os: Visual Studio 2015
platform:
- x86
- x64
environment:
  CI_CODEPLEX_USER:
    secure: HW7bjsXQTL9wIwYhN8WQpg==
  CI_CODEPLEX_PASSWORD:
    secure: 0VuHba1FogMX3TBBC2RJQw==
  CI_PUBLISHAPPID:
    secure: fe++r3+ZTiE0b0TPHw+6hF/dLxYoiDpDogcEJXmt4OAk58QbSqeLnSmP1a3OJcOL
  CI_PUBLISHKEY:
    secure: 1UdlmNO7NURkAOSxs1nLS7C5PWwY0QyqFSh3Au1aQhZzMWTgUgaW/8ZNdVuMW7Mi
  DE_PFX_KEY:
    secure: p7A0E/BfE4md3QJjC+BsCw==
  VS_PFX_KEY:
    secure: DJ/nrcNs85BUM9EiPfPWCr526TUk7WgPnN9PIAiI8lU=
  ProductionApiDomain: de.bit13.com
  DevelopmentApiDomain: de.bit13.local
  ReleaseMode: Setup
  CI_PROJECT_FRIENDLY_NAME: Droid Explorer
  PUSHBULLET_API_TOKEN:
    secure: 2MwCYfQNYPfPjDqNJ1EL8VrIydQNRz3MfhnuI9dzSZag9JwCnqk5k3mMYTFn4ORk
  PUBLISH_BIT13_FTP_USER:
    secure: 0Nee1P3hK6TB+BCEcPczQoGBqcRb8lJ3FHnmW6P3s3w=
  PUBLISH_BIT13_FTP_HOST:
    secure: KxS2LdlWc3kX+FsmbQLj7A==
hosts:
  de.bit13.local: 69.245.210.157
install:
- ps: .\.appveyor\appveyor.install.ps1
before_build:
- ps: >-
    nuget.exe restore

    .\.appveyor\appveyor.before-build.ps1
build:
  project: .\.build\BuildDroidExplorer.msbuild
  verbosity: minimal
after_build:
- ps: .\.appveyor\appveyor.after-build.ps1
artifacts:
- path: /\\$(APPVEYOR_PROJECT_NAME).*\.setup\.zip$/
  name: Zip
before_deploy:
- ps: .\.appveyor\appveyor.before-deployment.ps1
deploy:
- provider: GitHub
  tag: $(APPVEYOR_PROJECT_NAME)-v$(CI_BUILD_VERSION)
  release: $(APPVEYOR_PROJECT_NAME)-v$(CI_BUILD_VERSION)
  description: $(CI_RELEASE_DESCRIPTION)
  auth_token:
    secure: UEgy2H9zJKLi599QoO3qVf5BKFqloRQ246ez9cEgsfV3vooAUfVopMS9+IjRtArL
  artifact: Zip
  on:
    branch: master
    CI_DEPLOY_GITHUB: True
- provider: FTP
  host: $(PUBLISH_BIT13_FTP_HOST)
  protocol: ftp
  username: $(PUBLISH_BIT13_FTP_USER)
  password:
    secure: nkPwqyw5PNWeJbPrHlaTaxuJD3aNlcOtX9ooupg/VIc=
  folder: /
  artifact: /\\$(APPVEYOR_PROJECT_NAME).*\.setup\.zip$/
  active_mode: false
  beta: true
  debug: true
  on:
    branch: master
    CI_DEPLOY_FTP: True
after_deploy:
- ps: .\.appveyor\appveyor.after-deployment.ps1